export const staticTableData0 = [
  {
    id: 10001,
    name: "Test1",
    role: "Develop",
    sex: "Man",
    age: 28,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10002,
    name: "Test2",
    role: "Test",
    sex: "Women",
    age: 22,
    address: "Guangzhou",
  },
  {
    id: 10003,
    name: "Test3",
    role: "PM",
    sex: "Man",
    age: 32,
    address: "Shanghai",
  },
  {
    id: 10004,
    name: "Test4",
    role: "Designer",
    sex: "Women",
    age: 24,
    address: "Shanghai",
  },
];

export const staticTableData1 = [
  {
    id: 10001,
    name: "Test1",
    role: "Develop",
    sex: "Man",
    age: 28,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10002,
    name: "Test2",
    role: "Test",
    sex: "Women",
    age: 22,
    address: "Guangzhou",
  },
  {
    id: 10003,
    name: "Test3",
    role: "PM",
    sex: "Man",
    age: 32,
    address: "Shanghai",
  },
  {
    id: 10004,
    name: "Test4",
    role: "Designer",
    sex: "Women",
    age: 23,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10005,
    name: "Test5",
    role: "Develop",
    sex: "Women",
    age: 30,
    address: "Shanghai",
  },
  {
    id: 10006,
    name: "Test6",
    role: "Designer",
    sex: "Women",
    age: 21,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10007,
    name: "Test7",
    role: "Test",
    sex: "Man",
    age: 29,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10008,
    name: "Test8",
    role: "Develop",
    sex: "Man",
    age: 35,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10009,
    name: "Test9",
    role: "Test",
    sex: "Man",
    age: 26,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10010,
    name: "Test10",
    role: "Develop",
    sex: "Man",
    age: 38,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10011,
    name: "Test11",
    role: "Test",
    sex: "Women",
    age: 29,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10012,
    name: "Test12",
    role: "Develop",
    sex: "Man",
    age: 27,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10013,
    name: "Test13",
    role: "Test",
    sex: "Women",
    age: 24,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10014,
    name: "Test14",
    role: "Develop",
    sex: "Man",
    age: 34,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10015,
    name: "Test15",
    role: "Test",
    sex: "Man",
    age: 21,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10016,
    name: "Test16",
    role: "Develop",
    sex: "Women",
    age: 20,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10017,
    name: "Test17",
    role: "Test",
    sex: "Man",
    age: 31,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10018,
    name: "Test18",
    role: "Develop",
    sex: "Women",
    age: 32,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10019,
    name: "Test19",
    role: "Test",
    sex: "Man",
    age: 37,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10020,
    name: "Test20",
    role: "Develop",
    sex: "Man",
    age: 41,
    address: "vxe-table 从入门到放弃",
  },
];

export const staticTableData2 = [
  {
    id: 10001,
    name: "Test1",
    role: "Develop",
    sex: "Man",
    age: 28,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10002,
    name: "Test2",
    role: "Test",
    sex: "Women",
    age: 22,
    address: "Guangzhou",
  },
  {
    id: 10003,
    name: "Test3",
    role: "PM",
    sex: "Man",
    age: 32,
    address: "Shanghai",
  },
  {
    id: 10004,
    name: "Test4",
    role: "Designer",
    sex: "Women",
    age: 23,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10005,
    name: "Test5",
    role: "Develop",
    sex: "Women",
    age: 30,
    address: "Shanghai",
  },
  {
    id: 10006,
    name: "Test6",
    role: "Designer",
    sex: "Women",
    age: 21,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10007,
    name: "Test7",
    role: "Test",
    sex: "Man",
    age: 29,
    address: "vxe-table 从入门到放弃",
  },
  {
    id: 10008,
    name: "Test8",
    role: "Develop",
    sex: "Man",
    age: 35,
    address: "vxe-table 从入门到放弃",
  },
];

export const staticTableData3 = [
  {
    name: "Test1",
    role: "前端",
    date: "内容显示原生 title",
    rate: 5,
    address: "address1",
  },
  {
    name: "内容超出隐藏，不显示提示信息xxxxxxxxxxxxxxxxxxx",
    role: "后端",
    date: "2020-02-22",
    rate: 2,
    address: "address2\ntooltip文本换行\n换行xx",
  },
  {
    name: "Test3",
    role: "内容超出一行显示为 tooltip xxxxxxxxxxxxxx",
    date: "2020-01-01",
    rate: 0,
    address: "address3\ntooltip文本换行\n换行xx",
  },
  {
    name: "Test4",
    role: "设计师",
    date: "2020-02-23",
    rate: 1,
    address: "address4",
  },
  {
    name: "Test5",
    role: "前端",
    date: "2020-01-20",
    rate: 3,
    address: "address5\ntooltip文本换行\n换行xx",
  },
];

export const staticTableData4 = [
  {
    id: 10001,
    name: "Test1",
    nickname: "T1",
    role: "Develop",
    sex: "0",
    sex2: ["0"],
    num1: 40,
    age: 28,
    address: "Shenzhen",
    date12: "",
    date13: "",
  },
  {
    id: 10002,
    name: "Test2",
    nickname: "T2",
    role: "Designer",
    sex: "1",
    sex2: ["0", "1"],
    num1: 44,
    age: 22,
    address: "Guangzhou",
    date12: "",
    date13: "2020-08-20",
  },
  {
    id: 10003,
    name: "Test3",
    nickname: "T3",
    role: "Test",
    sex: "0",
    sex2: ["1"],
    num1: 200,
    age: 32,
    address: "Shanghai",
    date12: "2020-09-10",
    date13: "",
  },
  {
    id: 10004,
    name: "Test4",
    nickname: "T4",
    role: "Designer",
    sex: "1",
    sex2: ["1"],
    num1: 30,
    age: 23,
    address: "Shenzhen",
    date12: "",
    date13: "2020-12-04",
  },
  {
    id: 10005,
    name: "Test5",
    nickname: "T5",
    role: "Develop",
    sex: "0",
    sex2: ["1", "0"],
    num1: 20,
    age: 30,
    address: "Shanghai",
    date12: "2020-09-20",
    date13: "",
  },
  {
    id: 10006,
    name: "Test6",
    nickname: "T6",
    role: "Designer",
    sex: "1",
    sex2: ["0"],
    num1: 10,
    age: 21,
    address: "Shenzhen",
    date12: "",
    date13: "",
  },
  {
    id: 10007,
    name: "Test7",
    nickname: "T7",
    role: "Develop",
    sex: "0",
    sex2: ["0"],
    num1: 5,
    age: 29,
    address: "Shenzhen",
    date12: "2020-01-02",
    date13: "2020-09-20",
  },
  {
    id: 10008,
    name: "Test8",
    nickname: "T8",
    role: "PM",
    sex: "1",
    sex2: ["0"],
    num1: 2,
    age: 35,
    address: "Shenzhen",
    date12: "",
    date13: "",
  },
];

export const staticTableData5 = [
  {
    id: 1000,
    name: "vxe-table 从入门到放弃1",
    type: "mp3",
    size: 1024,
    date: "2020-08-01",
  },
  {
    id: 1005,
    name: "Test2",
    type: "mp4",
    size: null,
    date: "2021-04-01",
    childs: [
      { id: 24300, name: "Test3", type: "avi", size: 1024, date: "2020-03-01" },
      {
        id: 20045,
        name: "vxe-table 从入门到放弃4",
        type: "html",
        size: 600,
        date: "2021-04-01",
      },
      {
        id: 10053,
        name: "vxe-table 从入门到放弃96",
        type: "avi",
        size: null,
        date: "2021-04-01",
        childs: [
          {
            id: 24330,
            name: "vxe-table 从入门到放弃5",
            type: "txt",
            size: 25,
            date: "2021-10-01",
          },
          {
            id: 21011,
            name: "Test6",
            type: "pdf",
            size: 512,
            date: "2020-01-01",
          },
          {
            id: 22200,
            name: "Test7",
            type: "js",
            size: 1024,
            date: "2021-06-01",
          },
        ],
      },
    ],
  },
  { id: 23666, name: "Test8", type: "xlsx", size: 2048, date: "2020-11-01" },
  {
    id: 24555,
    name: "vxe-table 从入门到放弃9",
    type: "avi",
    size: 224,
    date: "2020-10-01",
  },
];

export const columns0 = [
  { type: "seq", width: "38", align: "center" },
  { field: "name", title: "Name" },
  { field: "sex", title: "Sex" },
  { field: "age", title: "Age" },
];

export const columns1 = [
  { type: "seq", width: "38", align: "center" },
  { field: "name", title: "Name" },
  { field: "sex", title: "Sex" },
  { field: "age", title: "Age" },
  { field: "address", title: "Address" },
];

export const columns2 = [
  { type: "seq", width: "38", fixed: "left", align: "center" },
  { field: "name", title: "Name", width: "300" },
  { field: "sex", title: "Sex", width: "250" },
  { field: "age", title: "Age", width: "250" },
  { field: "role", title: "Role", width: "300" },
  { field: "address", title: "Address", width: "350" },
];

export const columns3 = [
  { type: "radio", width: "38", align: "center" },
  { field: "name", title: "Name" },
  { field: "sex", title: "Sex" },
  { field: "age", title: "Age" },
  { field: "address", title: "Address" },
];

export const columns4 = [
  { type: "checkbox", width: "38", align: "center" },
  { field: "name", title: "Name" },
  { field: "sex", title: "Sex" },
  { field: "age", title: "Age" },
  { field: "address", title: "Address" },
];

export const columns5 = [
  { type: "seq", width: "38", align: "center" },
  { field: "name", title: "名称" },
  { field: "role", title: "角色" },
  { field: "date", title: "标题溢出，显示为 tooltip xxxxxxxxxx" },
  { field: "rate", title: "标题显示原生 title ___________________________" },
  {
    field: "address",
    title: "不换行不换行不换行不换行不换行不换行不换行不换行不换行",
    width: "160",
  },
];
